### ISSUE TITLE
Support multiple table definitions per file

### ISSUE THREAD

**Issue by tobz1000** [ehmpathy/sql-code-generator#47]
I have a db schema exported as a single `.sql` file, defining ~50 tables. Running `sql-code-generator generate` on this file only produces a type definition for the first table. Is it possible to produce type definitions for multiple tables/schema items from a single schema file?

**Comment by uladkasach** [comment]
it should be possible - and seems like a valid use case for this project :+1:  

could you confirm that in your case the `create` statements are delimited by `;`?

Wondering what a good way to distinguish independent statements would be:
- `;` should be a reliable delimiter for `tables` and `views`
- `functions` can have `;` inside the logic-body of their declarations, so will need to do something special for those cases - but this shouldn't be too complicated since they declare their "begin-body/end-body" blocks explicitly.

**Comment by tobz1000** [comment]
Nice, this would be helpful :)

> could you confirm that in your case the `create` statements are delimited by `;`?

Yes, the schema file is a series of entries like this, separated by line breaks:

```sql
-- Create syntax for TABLE 'features'
CREATE TABLE `features` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `video` text,
  `tag` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

**Comment by BoilerTom90** [comment]
I'd like to add to this request given my experience with it... 

I've been trying to use the output of `mysqldump` and every time it would error out saying it couldn't parse the schema file. Only after much experimenting did I realize that there were a few problems going on:

- the package doesn't support multiple create table statements in the same file, so this enhancement request is much needed.
- the package errors out if it sees something other than create table statements. `mysqldump` outputs a whole lot more (such as drop table statements, insert statements, etc.).  But, thankfully, those can be omitted with the appropriate options to `mysqldump` 

- the output of `mysqldump` has a lot of "crap" in it that needs to be ignored by any parser trying to use it.  For example, for some reason, it outputs a lot of one-line comments, i.e. /* xxx */  with a semi-colon at the end of the line. Even if I use the option to omit the comments, it still outputs the extra semi-colons. The extra semi-colon was causing the tool tool to error out. Those would need to be ignored.

For your convenience, I've attached the output of `mysqldump` from my local database.

[mysqldump.schema.txt](https://github.com/ehmpathy/sql-code-generator/files/11001703/mysqldump.schema.txt)

**Comment by Benjythebee** [comment]
bump on this

**Comment by jonarnaldo** [comment]
bump as well! 🙏

**Comment by uladkasach** [comment]
This is now supported :tada: 

Here's an example: the types that were generated for the mysqldump shared by @BoilerTom90 above. (Thank you for that, used it directly as a test case): https://github.com/ehmpathy/sql-code-generator/commit/5f6e920401badabc033463eb6362392620ba4012#diff-ed2a9966bc088b8e9967bd9e06ee829ba5fe789e50dca8fa7e037ec2e4584aaaR262-R337
