### ISSUE TITLE
Make config "queries" field optional/improve error message

### ISSUE THREAD

**Issue by tobz1000** [ehmpathy/sql-code-generator#48]
It seems to me that the "queries" field in `codegen.sql.yml` could be optional. In my case, I'm not generating code for any sql queries, but the generator doesn't run without a non-empty query filepath list. Currently I'm just using:

```yml
queries:
  - "[node]"
```

to placate the config parser.

Additionally, the error message when this section is not included could be improved. I see: `TypeError: Patterns must be a string (non empty) or an array of strings` with no indication of the origin of the error.

**Comment by uladkasach** [comment]
agreed - good call!

i'll plan to do this, feel free to submit a pr if you need it done sooner though

**Comment by uladkasach** [comment]
this is now supported
